#ifndef TOKENISER_H
#define TOKENISER_H

enum TOKEN {
    FEOF, UNKNOWN, NUMBER, ID, STRINGCONST,
    RBRACKET, LBRACKET, RPARENT, LPARENT, COMMA,
    SEMICOLON, DOT, ADDOP, MULOP, RELOP, NOT, ASSIGN,
    IF, THEN, ELSE, WHILE, DO, FOR, TO, BEGIN_TOKEN, END_TOKEN, DISPLAY
};



#endif
